config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # home
  root 'home#index'
  get 'home/users' => 'home#users'
  resources :home, only: [:destroy, :show]
  # post
  resources :posts, only: [:create]
  # comment
  resources :comments, only: [:create]
  # follows
  post '/follows/create' => 'follows#create'
  post '/follows/destroy' => 'follows#destroy'
  # devise
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    confirmations: 'users/confirmations'
    }
  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  # sidekiq
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: '/sidekiq'
    ActiveAdmin.routes(self)
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar nav-bg-color navbar-dark">
  <a class="navbar-brand" href="/"><%= ApplicationHelper::APP_NAME %></a>
  <% if user_signed_in? %>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <%= link_to("#", id: "navbarDropdownMenuLink", class: "nav-link dropdown-toggle", "data-toggle": "dropdown", "data-flip": "true", "aria-haspopup": "false", "area-expanded": "false") do %>
          <%= image_tag current_user.avatar.url, class: "rounded-circle", style: "width: 50px;" %>
        <% end %>

        <div class="dropdown-menu dropdown-memu-right" area-labelledby="navbarDropdownMenuLink" style="position: absolute;right: 0;left: auto;">
          <%= link_to "ユーザ一覧", home_users_path, class: "dropdown-item" %>
          <%= link_to "プロフィール編集", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "ログアウト", users_sign_out_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container py-4">
      <%= flash_message(flash[:success], :success) if flash[:success]%>
      <%= flash_message(flash[:error], :danger) if flash[:error]%>
      <%= flash_message(flash[:alert], :warning) if flash[:alert]%>
      <%= flash_message(flash[:notice], :info) if flash[:notice]%>
      <%= yield %>
    </div>
  </body>
</html>